"""empty message

Revision ID: 21cbc671923f
Revises: 3ef6e3e24b8b
Create Date: 2019-08-28 12:19:47.735882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cbc671923f'
down_revision = '3ef6e3e24b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misc_service',
    sa.Column('serviceID', sa.String(length=20), nullable=False),
    sa.Column('serviceType', sa.String(length=20), nullable=True),
    sa.Column('serviceAbbr', sa.String(length=10), nullable=True),
    sa.Column('reportType', sa.String(length=5), nullable=True),
    sa.Column('description', sa.String(length=144), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('serviceID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('misc_service')
    # ### end Alembic commands ###
