"""Doctors and Clinics Tables

Revision ID: 33d717f28276
Revises: c02106a8ec4b
Create Date: 2019-08-12 10:49:23.404817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d717f28276'
down_revision = 'c02106a8ec4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
    sa.Column('clinicSerialNum', sa.String(length=64), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('street', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('clinicSerialNum'),
    sa.UniqueConstraint('company'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('doctor',
    sa.Column('doctorSerialNum', sa.String(length=64), nullable=False),
    sa.Column('first', sa.String(length=24), nullable=True),
    sa.Column('middle', sa.String(length=3), nullable=True),
    sa.Column('last', sa.String(length=24), nullable=True),
    sa.Column('cell', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.Column('salutation', sa.String(length=4), nullable=True),
    sa.Column('clinicSerialNum', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['clinicSerialNum'], ['clinic.clinicSerialNum'], ),
    sa.PrimaryKeyConstraint('doctorSerialNum')
    )
    op.create_index(op.f('ix_doctor_doctorSerialNum'), 'doctor', ['doctorSerialNum'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_doctorSerialNum'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_table('clinic')
    # ### end Alembic commands ###
