"""empty message

Revision ID: 718373a1d59d
Revises: 7ffdf761c3b4
Create Date: 2019-08-15 15:21:45.702928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718373a1d59d'
down_revision = '7ffdf761c3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_US', sa.Column('mvr4seasons', sa.String(length=8), nullable=True))
    op.drop_column('report_US', 'mvr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_US', sa.Column('mvr', sa.BOOLEAN(), nullable=True))
    op.drop_column('report_US', 'mvr4seasons')
    # ### end Alembic commands ###
