"""empty message

Revision ID: 7ffdf761c3b4
Revises: 80975f2a9010
Create Date: 2019-08-15 15:12:09.323021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ffdf761c3b4'
down_revision = '80975f2a9010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_US', sa.Column('mvr', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_US', 'mvr')
    # ### end Alembic commands ###
