"""reset db

Revision ID: 80975f2a9010
Revises: 
Create Date: 2019-08-14 15:20:23.085574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80975f2a9010'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
    sa.Column('clinicSerialNum', sa.String(length=64), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('street', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('clinicSerialNum'),
    sa.UniqueConstraint('company'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('report_US',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docSerialNum', sa.String(length=20), nullable=True),
    sa.Column('patient', sa.String(length=24), nullable=True),
    sa.Column('owner', sa.String(length=24), nullable=True),
    sa.Column('species', sa.String(length=6), nullable=True),
    sa.Column('breed', sa.String(length=24), nullable=True),
    sa.Column('sexPatient', sa.String(length=2), nullable=True),
    sa.Column('agePatient', sa.String(length=24), nullable=True),
    sa.Column('clinicalHistory', sa.String(length=360), nullable=True),
    sa.Column('SF_Liver', sa.String(length=12), nullable=True),
    sa.Column('SF_Spleen', sa.String(length=12), nullable=True),
    sa.Column('SF_Stomach', sa.String(length=12), nullable=True),
    sa.Column('SF_Pancreas', sa.String(length=12), nullable=True),
    sa.Column('SF_Intestines', sa.String(length=12), nullable=True),
    sa.Column('SF_Adrenals', sa.String(length=12), nullable=True),
    sa.Column('SF_LKidney', sa.String(length=12), nullable=True),
    sa.Column('SF_RKidney', sa.String(length=12), nullable=True),
    sa.Column('SF_Bladder', sa.String(length=12), nullable=True),
    sa.Column('SF_Sublum', sa.String(length=12), nullable=True),
    sa.Column('SF_Prostate', sa.String(length=12), nullable=True),
    sa.Column('SF_Uterus', sa.String(length=12), nullable=True),
    sa.Column('Conclusions_ALL', sa.String(length=360), nullable=True),
    sa.Column('FINDAS_ALL', sa.String(length=360), nullable=True),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('clinicSerialNum', sa.Integer(), nullable=True),
    sa.Column('clinicName', sa.String(length=24), nullable=True),
    sa.Column('doctor', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('doctor',
    sa.Column('doctorSerialNum', sa.String(length=64), nullable=False),
    sa.Column('first', sa.String(length=24), nullable=True),
    sa.Column('middle', sa.String(length=3), nullable=True),
    sa.Column('last', sa.String(length=24), nullable=True),
    sa.Column('cell', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.Column('salutation', sa.String(length=4), nullable=True),
    sa.Column('clinicName', sa.String(length=20), nullable=True),
    sa.Column('clinicSerialNum', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['clinicSerialNum'], ['clinic.clinicSerialNum'], ),
    sa.PrimaryKeyConstraint('doctorSerialNum')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('report_US')
    op.drop_table('clinic')
    # ### end Alembic commands ###
