"""empty message

Revision ID: a22d627e1973
Revises: bcdded6564d1
Create Date: 2020-02-04 16:48:40.096031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22d627e1973'
down_revision = 'bcdded6564d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report__echo', sa.Column('species', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report__echo', 'species')
    # ### end Alembic commands ###
