"""empty message

Revision ID: bcdded6564d1
Revises: 25c846a6302c
Create Date: 2020-01-14 13:46:37.230858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdded6564d1'
down_revision = '25c846a6302c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('invoiceID', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('mvr4seasons', sa.String(length=24), nullable=True),
    sa.Column('clinic', sa.String(length=64), nullable=True),
    sa.Column('clinicSerialNum', sa.String(length=20), nullable=True),
    sa.Column('doctor', sa.String(length=24), nullable=True),
    sa.Column('docSerialNum', sa.String(length=20), nullable=True),
    sa.Column('svcTotal', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinicSerialNum'], ['clinic.clinicSerialNum'], ),
    sa.ForeignKeyConstraint(['docSerialNum'], ['doctor.doctorSerialNum'], ),
    sa.PrimaryKeyConstraint('invoiceID')
    )
    op.create_index(op.f('ix_invoice_timestamp'), 'invoice', ['timestamp'], unique=False)
    op.create_table('invoice__item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('invoiceID', sa.String(length=20), nullable=True),
    sa.Column('serviceType', sa.String(length=20), nullable=True),
    sa.Column('reportID', sa.Integer(), nullable=True),
    sa.Column('patient', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoiceID'], ['invoice.invoiceID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice__item_timestamp'), 'invoice__item', ['timestamp'], unique=False)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_invoice__item_timestamp'), table_name='invoice__item')
    op.drop_table('invoice__item')
    op.drop_index(op.f('ix_invoice_timestamp'), table_name='invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###
