"""Ultrasound table

Revision ID: c02106a8ec4b
Revises: cc3919b6246e
Create Date: 2019-07-26 10:17:19.579687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02106a8ec4b'
down_revision = 'cc3919b6246e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_US',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_KF_Doctor', sa.String(length=140), nullable=True),
    sa.Column('patient', sa.String(length=24), nullable=True),
    sa.Column('owner', sa.String(length=24), nullable=True),
    sa.Column('species', sa.String(length=6), nullable=True),
    sa.Column('breed', sa.String(length=24), nullable=True),
    sa.Column('sexPatient', sa.String(length=2), nullable=True),
    sa.Column('agePatient', sa.String(length=24), nullable=True),
    sa.Column('clinicalHistory', sa.String(length=140), nullable=True),
    sa.Column('SF_Liver', sa.String(length=12), nullable=True),
    sa.Column('SF_Spleen', sa.String(length=12), nullable=True),
    sa.Column('SF_Stomach', sa.String(length=12), nullable=True),
    sa.Column('SF_Pancreas', sa.String(length=12), nullable=True),
    sa.Column('SF_Intestines', sa.String(length=12), nullable=True),
    sa.Column('SF_Adrenals', sa.String(length=12), nullable=True),
    sa.Column('SF_LKidney', sa.String(length=12), nullable=True),
    sa.Column('SF_RKidney', sa.String(length=12), nullable=True),
    sa.Column('SF_Bladder', sa.String(length=12), nullable=True),
    sa.Column('SF_Sublum', sa.String(length=12), nullable=True),
    sa.Column('SF_Prostate', sa.String(length=12), nullable=True),
    sa.Column('SF_Uterus', sa.String(length=12), nullable=True),
    sa.Column('Conclusions_ALL', sa.String(length=360), nullable=True),
    sa.Column('FINDAS_ALL', sa.String(length=360), nullable=True),
    sa.Column('MVI_SIG_Doctor', sa.String(length=12), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('clinicSerialNum', sa.Integer(), nullable=True),
    sa.Column('clinicName', sa.String(length=24), nullable=True),
    sa.Column('doctor', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_US_date'), 'report_US', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_US_date'), table_name='report_US')
    op.drop_table('report_US')
    # ### end Alembic commands ###
