"""empty message

Revision ID: f92987044805
Revises: 21cbc671923f
Create Date: 2019-09-06 12:25:09.323748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92987044805'
down_revision = '21cbc671923f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report__misc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.String(length=24), nullable=True),
    sa.Column('docSerialNum', sa.String(length=20), nullable=True),
    sa.Column('clinicSerialNum', sa.Integer(), nullable=True),
    sa.Column('clinicName', sa.String(length=24), nullable=True),
    sa.Column('mvr4seasons', sa.String(length=24), nullable=True),
    sa.Column('patient', sa.String(length=24), nullable=True),
    sa.Column('owner', sa.String(length=24), nullable=True),
    sa.Column('service', sa.String(length=24), nullable=True),
    sa.Column('SvcTotal', sa.Numeric(), nullable=True),
    sa.Column('Misc_Service_Description', sa.String(length=300), nullable=True),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report__misc')
    # ### end Alembic commands ###
